Repository sotobabi/betty, pull requests merged in 2019-04, with the labels that each got.

#1 Remove unused class and changed path of the app to work under root
  src/main/java/com/codingnomads/betty/config/WebMvcConfig.java
  src/main/java/com/codingnomads/betty/controller/HelloController.java
Labels: Ready for Review

#2 war file is ready for deployment
  build.gradle
  src/main/java/com/codingnomads/betty/BettyApplication.java
Labels: Ready to Merge

#7 Create travis configuration
  .travis.yml
  README.md
  scripts/deploy.sh
Labels: Ready for Review

#8 Fix JenkinsFile
  Jenkinsfile
Labels: Ready for Review

#9 Added the sentiment score pojo
  src/main/java/com/codingnomads/betty/logic/models/TeamSentimentScore.java
  src/main/java/com/codingnomads/betty/presentation/controller/HelloController.java
Labels: Ready for Review

#10 Created deployment script and encryption travis logic
  .travis.yml
  scripts/deploy.sh
  secrets/betty-webserver-key.pem.enc
Labels: Ready for Review

#15 Added test folders and two initial tests. Also, documentation
  gradle/wrapper/gradle-wrapper.properties
  src/test/com/codingnomads/betty/BettyApplicationTests.java
Labels: Ready for Review

#16 Completed rudimentary probability implementation
  Jenkinsfile
  src/main/java/com/codingnomads/betty/logic/exceptions/InvalidScoreException.java
  src/main/java/com/codingnomads/betty/logic/models/TeamProbabilityToWin.java
  src/main/java/com/codingnomads/betty/logic/services/ProbabilityToWinService.java
  src/test/java/com/codingnomads/betty/BettyApplicationTests.java
  src/test/java/com/codingnomads/betty/logic/services/ProbabilityToWinServiceTests.java
Labels: Ready for Review

#18 Roi/sonarqube
  .travis.yml
  README.md
  build.gradle
  sonar-project.properties
Labels: Ready to Merge

#17 Alp/consume api
  build.gradle
  src/main/java/com/codingnomads/betty/BettyApplication.java
  src/main/java/com/codingnomads/betty/configurations/TwitterConfigurer.java
  src/main/java/com/codingnomads/betty/database/TwitterSourceRepository.java
  src/main/java/com/codingnomads/betty/logic/exceptions/TwitterSearchFailedException.java
  src/main/java/com/codingnomads/betty/logic/repositories/TwitterRepository.java
  src/main/java/com/codingnomads/betty/logic/services/TwitterService.java
  src/main/java/com/codingnomads/betty/presentation/controller/HelloController.java
  src/test/java/com/codingnomads/betty/database/TwitterSourceRepositoryTest.java
Labels: Ready for Review

#21 Cristian/add database connectivity
  .travis.yml
  build.gradle
  sonar-project.properties
  src/main/java/com/codingnomads/betty/data/api/TwitterSourceRepository.java
  src/main/java/com/codingnomads/betty/data/models/Tweet.java
  src/main/java/com/codingnomads/betty/logic/interfaces/TwitterRepository.java
  src/main/java/com/codingnomads/betty/logic/services/TwitterService.java
  src/main/java/com/codingnomads/betty/presentation/controller/HelloController.java
  src/main/resources/application.properties
  src/test/java/com/codingnomads/betty/data/api/TwitterSourceRepositoryTest.java
  src/test/java/com/codingnomads/betty/logic/services/ProbabilityToWinServiceTests.java
  src/test/java/com/codingnomads/betty/logic/services/TwitterServiceTests.java
Labels: Ready to Merge

#26 Cleaning up debugging parameters since server is back up
  src/main/java/com/codingnomads/betty/BettyApplication.java
  src/main/resources/application.properties
Labels: Ready for Review

#19 Integrate coreNLP
  build.gradle
  src/main/java/com/codingnomads/betty/configuration/SentimentAnalysisConfig.java
  src/main/java/com/codingnomads/betty/logic/models/SentimentClassification.java
  src/main/java/com/codingnomads/betty/logic/models/SentimentResult.java
  src/main/java/com/codingnomads/betty/logic/services/InvalidInputException.java
  src/main/java/com/codingnomads/betty/logic/services/SentimentAnalyserService.java
  src/main/java/com/codingnomads/betty/presentation/controller/PresentationController.java
  src/test/java/com/codingnomads/betty/logic/services/SentimentAnalyserServiceTest.java
Labels: Comments pending

#29 Fixed minor varchar length issue in DB
  src/main/java/com/codingnomads/betty/data/models/Tweet.java
Labels: Ready for Review

#30 Parametirized DB DNS and Name. Added env vars to Travis and Tomcat
  src/main/resources/application.properties
Labels: Ready for Review

#31 Alp/consuming bet api
  src/main/java/com/codingnomads/betty/configurations/RestTemplateConfigure.java
  src/main/java/com/codingnomads/betty/data/api/GameInformationAPIRepository.java
  src/main/java/com/codingnomads/betty/logic/exceptions/JSONNotFoundException.java
  src/main/java/com/codingnomads/betty/logic/interfaces/GameInformationRepository.java
  src/main/java/com/codingnomads/betty/logic/models/betAPImodels/EventJSON.java
  src/main/java/com/codingnomads/betty/logic/models/betAPImodels/GameInformationJSON.java
  src/main/java/com/codingnomads/betty/logic/models/betAPImodels/MarketJSON.java
  src/main/java/com/codingnomads/betty/logic/models/betAPImodels/PriceJSON.java
  src/main/java/com/codingnomads/betty/logic/models/betAPImodels/RunnerJSON.java
  src/main/java/com/codingnomads/betty/logic/services/GameInformationService.java
  src/test/java/com/codingnomads/betty/logic/services/GameInformationServiceTest.java
Labels: Ready to Merge

#28 Eileen/integration (WIP)
  sonar-project.properties
  src/main/java/com/codingnomads/betty/data/models/Tweet.java
  src/main/java/com/codingnomads/betty/logic/models/TeamSentimentScore.java
  src/main/java/com/codingnomads/betty/logic/services/AnalyzeTweetsService.java
  src/main/java/com/codingnomads/betty/logic/services/ProbabilityToWinService.java
  src/main/java/com/codingnomads/betty/logic/services/SentimentAnalyserService.java
  src/main/java/com/codingnomads/betty/logic/services/TwitterService.java
  src/main/java/com/codingnomads/betty/presentation/controller/HelloController.java
  src/main/java/com/codingnomads/betty/presentation/controller/HomeController.java
  src/main/java/com/codingnomads/betty/presentation/controller/SearchController.java
  src/main/java/com/codingnomads/betty/presentation/webmodel/InputTeam.java
  src/main/resources/templates/getOdds.html
  src/main/resources/templates/index.html
  src/test/java/com/codingnomads/betty/BettyApplicationTests.java
  src/test/java/com/codingnomads/betty/logic/services/AnalyzeTweetsServiceTest.java
  src/test/java/com/codingnomads/betty/logic/services/ProbabilityToWinServiceTests.java
  src/test/java/com/codingnomads/betty/logic/services/SentimentAnalyserServiceTest.java
  src/test/java/com/codingnomads/betty/logic/services/TwitterServiceTests.java
  src/test/java/com/codingnomads/betty/presentation/controller/HomeControllerTest.java
  src/test/java/com/codingnomads/betty/presentation/controller/SearchControllerTests.java
Labels: Ready to Merge

#32 Twitter Credentials at Env Variable
  src/main/java/com/codingnomads/betty/configurations/TwitterConfig.java
  src/main/resources/application.properties
Labels: Ready to Merge

#33 Finished Initial Spring Batch implementation into Betty
  build.gradle
  sonar-project.properties
  src/main/java/com/codingnomads/betty/configurations/SpringBatchConfig.java
  src/main/java/com/codingnomads/betty/data/batch/Processor.java
  src/main/java/com/codingnomads/betty/data/batch/RdsWriter.java
  src/main/java/com/codingnomads/betty/data/batch/models/StatusItemReader.java
  src/main/java/com/codingnomads/betty/data/models/Tweet.java
  src/main/java/com/codingnomads/betty/presentation/controller/BatchController.java
  src/main/resources/application.properties
  src/test/java/com/codingnomads/betty/data/batch/ProcessorTests.java
Labels: Ready for Review
