Repository sotobabi/betty, pull requests merged in 2019-05, with the labels that each got.

#34 Game Odds Are Adding to Database
  src/main/java/com/codingnomads/betty/data/models/MatchOdds.java
  src/main/java/com/codingnomads/betty/logic/interfaces/MatchOddsJpaRepository.java
  src/main/java/com/codingnomads/betty/logic/services/GameInformationService.java
  src/test/java/com/codingnomads/betty/logic/services/GameInformationServiceTest.java
Labels: Ready to Merge

#35 Cristian/add scheduler for batch
  sonar-project.properties
  src/main/java/com/codingnomads/betty/data/batch/BatchScheduler.java
  src/main/java/com/codingnomads/betty/data/models/Tweet.java
  src/main/java/com/codingnomads/betty/presentation/controller/BatchController.java
Labels: Ready for Review

#36 Updates to Integration Class
  sonar-project.properties
  src/main/java/com/codingnomads/betty/logic/models/SentimentClassification.java
  src/main/java/com/codingnomads/betty/logic/models/SentimentResult.java
  src/main/java/com/codingnomads/betty/logic/models/TeamProbabilityToWin.java
  src/main/java/com/codingnomads/betty/logic/models/TeamSentimentScore.java
  src/main/java/com/codingnomads/betty/logic/services/SourceToResultPipelineService.java
  src/main/java/com/codingnomads/betty/presentation/controller/SearchController.java
  src/main/resources/templates/calculateOdds.html
  src/main/resources/templates/displayOdds.html
  src/main/resources/templates/index.html
  src/test/java/com/codingnomads/betty/logic/services/SourceToResultPipelineServiceTest.java
  src/test/java/com/codingnomads/betty/presentation/controller/SearchControllerTests.java
Labels: Ready to Merge

#39 Alp/saving odds spring batch
  src/main/java/com/codingnomads/betty/BettyApplication.java
  src/main/java/com/codingnomads/betty/configurations/SpringBatchConfig.java
  src/main/java/com/codingnomads/betty/data/api/TwitterSourceMinerRepository.java
  src/main/java/com/codingnomads/betty/data/batch/BatchScheduler.java
  src/main/java/com/codingnomads/betty/data/batch/batchprocessors/MatchOddsBatchProcessor.java
  src/main/java/com/codingnomads/betty/data/batch/batchprocessors/StatusProcessor.java
  src/main/java/com/codingnomads/betty/data/batch/batchreaders/MatchOddsReader.java
  src/main/java/com/codingnomads/betty/data/batch/batchreaders/StatusItemReader.java
  src/main/java/com/codingnomads/betty/data/batch/batchwriters/MatchOddsRdsWriter.java
  src/main/java/com/codingnomads/betty/data/batch/batchwriters/TweetsRdsWriter.java
  src/main/java/com/codingnomads/betty/data/batch/scheduler/BatchScheduler.java
  src/main/java/com/codingnomads/betty/data/models/MatchOdds.java
  src/main/java/com/codingnomads/betty/logic/services/GameInformationService.java
  src/main/resources/application.properties
  src/test/java/com/codingnomads/betty/data/api/TwitterSourceRepositoryTest.java
  src/test/java/com/codingnomads/betty/data/batch/batchprocessors/MatchOddsBatchProcessorTest.java
  src/test/java/com/codingnomads/betty/data/batch/batchprocessors/StatusProcessorTests.java
  src/test/java/com/codingnomads/betty/data/batch/batchreaders/MatchOddsReaderTests.java
  src/test/java/com/codingnomads/betty/data/batch/batchwriters/MatchOddsRdsWriterTests.java
  src/test/java/com/codingnomads/betty/data/batch/scheduler/BatchSchedulerTests.java
Labels: Ready for Review

#40 Annotations removed from test codes
  src/test/java/com/codingnomads/betty/data/batch/batchprocessors/StatusProcessorTests.java
  src/test/java/com/codingnomads/betty/logic/services/AnalyzeTweetsServiceTest.java
  src/test/java/com/codingnomads/betty/logic/services/GameInformationServiceTest.java
  src/test/java/com/codingnomads/betty/logic/services/ProbabilityToWinServiceTest.java
  src/test/java/com/codingnomads/betty/logic/services/ProcessTweetsThroughNlpServiceTest.java
  src/test/java/com/codingnomads/betty/logic/services/SentimentAnalyserServiceTest.java
  src/test/java/com/codingnomads/betty/logic/services/TwitterServiceTests.java
Labels: Ready for Review

#43 Added error page as fallback
  src/main/java/com/codingnomads/betty/data/batch/batchreaders/StatusItemReader.java
  src/main/java/com/codingnomads/betty/presentation/controller/HomeController.java
  src/main/resources/application.properties
  src/main/resources/static/css/style.css
  src/main/resources/static/img/emoji.png
  src/main/resources/templates/error.html
  src/test/java/com/codingnomads/betty/BettyApplicationTests.java
  src/test/java/com/codingnomads/betty/presentation/controller/HomeControllerTest.java
Labels: Ready for Review

#46 Solved security vulnerabilities in front-end
  src/main/resources/static/package-lock.json
  src/main/resources/static/package.json
Labels: Ready for Review

#45 Jordan sentimentscoredebug
  src/main/java/com/codingnomads/betty/logic/services/SourceToResultPipelineService.java
  src/test/java/com/codingnomads/betty/logic/services/ProcessTweetsThroughNlpServiceTest.java
  src/test/java/com/codingnomads/betty/logic/services/SentimentAnalyserServiceTest.java
Labels: Ready to Merge

#48 Cristian/display list matches odds frontend
  src/main/java/com/codingnomads/betty/data/models/MatchOdds.java
  src/main/java/com/codingnomads/betty/logic/interfaces/MatchOddsJpaRepository.java
  src/main/java/com/codingnomads/betty/logic/services/GameInformationService.java
  src/main/java/com/codingnomads/betty/presentation/controller/OddsByMatchController.java
  src/main/resources/templates/fragments/teamsAndOddsTable.html
  src/main/resources/templates/odds-by-match.html
  src/test/java/com/codingnomads/betty/presentation/controller/OddsByMatchControllerTest.java
Labels: Ready for Review

#47 Alp/improve odd api
  src/main/java/com/codingnomads/betty/configurations/SpringBatchConfig.java
  src/main/java/com/codingnomads/betty/data/batch/batchprocessors/FootballMatchProcessor.java
  src/main/java/com/codingnomads/betty/data/batch/batchprocessors/MatchOddsBatchProcessor.java
  src/main/java/com/codingnomads/betty/data/batch/batchprocessors/MatchToOddsProcessor.java
  src/main/java/com/codingnomads/betty/data/batch/batchreaders/FootballMatchApiReader.java
  src/main/java/com/codingnomads/betty/data/batch/batchreaders/FootballMatchJpaReader.java
  src/main/java/com/codingnomads/betty/data/batch/batchreaders/MatchOddsReader.java
  src/main/java/com/codingnomads/betty/data/batch/batchreaders/StatusItemReader.java
  src/main/java/com/codingnomads/betty/data/batch/batchwriters/FootballMatchRdsWriter.java
  src/main/java/com/codingnomads/betty/data/batch/batchwriters/MatchOddsRdsWriter.java
  src/main/java/com/codingnomads/betty/data/batch/exceptions/EmptyItemException.java
  src/main/java/com/codingnomads/betty/data/batch/scheduler/BatchScheduler.java
  src/main/java/com/codingnomads/betty/data/models/FootballMatchInfo.java
  src/main/java/com/codingnomads/betty/logic/interfaces/FootballMatchesInfoJpaRepository.java
  src/main/java/com/codingnomads/betty/logic/interfaces/MatchOddsJpaRepository.java
  src/main/java/com/codingnomads/betty/logic/models/betAPImodels/EventJSON.java
  src/main/java/com/codingnomads/betty/logic/services/GameInformationService.java
  src/main/java/com/codingnomads/betty/presentation/controller/HomeController.java
  src/test/java/com/codingnomads/betty/data/batch/batchprocessors/FootballMatchProcessorTests.java
  src/test/java/com/codingnomads/betty/data/batch/batchprocessors/MatchOddsBatchProcessorTest.java
  src/test/java/com/codingnomads/betty/data/batch/batchprocessors/MatchToOddsProcessorTests.java
  src/test/java/com/codingnomads/betty/data/batch/batchprocessors/StatusProcessorTests.java
  src/test/java/com/codingnomads/betty/data/batch/batchreaders/FootballMatchApireaderTests.java
  src/test/java/com/codingnomads/betty/data/batch/batchreaders/FootballMatchJpaReaderTests.java
  src/test/java/com/codingnomads/betty/data/batch/batchreaders/MatchOddsReaderTests.java
  src/test/java/com/codingnomads/betty/data/batch/batchwriters/FootballMatchRdsWriterTests.java
  src/test/java/com/codingnomads/betty/data/batch/batchwriters/MatchOddsRdsWriterTests.java
  src/test/java/com/codingnomads/betty/data/batch/scheduler/BatchSchedulerTests.java
  src/test/java/com/codingnomads/betty/logic/services/GameInformationServiceTest.java
Labels: Ready for Review

#49 sql query fix
  src/main/java/com/codingnomads/betty/logic/interfaces/FootballMatchesInfoJpaRepository.java
Labels: Ready to Merge

#53 Cristian/delete analyze tweet service
  src/main/java/com/codingnomads/betty/data/batch/tweetsjobs/awayteamjob/AwayTeamStatusItemReader.java
  src/main/java/com/codingnomads/betty/data/batch/tweetsjobs/exceptions/LackOfUpdatedMatchDataExc.java
  src/main/java/com/codingnomads/betty/data/batch/tweetsjobs/hometeamjob/HomeTeamStatusItemReader.java
  src/main/java/com/codingnomads/betty/logic/services/AnalyzeTweetsService.java
  src/main/java/com/codingnomads/betty/presentation/controller/SearchController.java
  src/main/resources/templates/calculateOdds.html
  src/main/resources/templates/fragments/navBar.html
  src/test/java/com/codingnomads/betty/logic/services/AnalyzeTweetsServiceTest.java
  src/test/java/com/codingnomads/betty/presentation/controller/SearchControllerTest.java
Labels: Ready to Merge

#51 Eileen/improve twitter searches
  src/main/java/com/codingnomads/betty/configurations/TwitterConfig.java
  src/main/java/com/codingnomads/betty/data/api/TwitterSourceMinerRepository.java
  src/main/java/com/codingnomads/betty/logic/interfaces/TwitterMinerRepository.java
  src/main/java/com/codingnomads/betty/logic/services/TwitterService.java
  src/test/java/com/codingnomads/betty/data/api/TwitterSourceRepositoryTest.java
Labels: Ready to Merge

#54 game service deleted 2 new service created
  src/main/java/com/codingnomads/betty/data/api/GameInformationAPIRepository.java
  src/main/java/com/codingnomads/betty/data/batch/footballmatchjob/FootballMatchApiReader.java
  src/main/java/com/codingnomads/betty/data/batch/footballmatchjob/FootballMatchProcessor.java
  src/main/java/com/codingnomads/betty/data/batch/footballmatchjob/FootballMatchRdsWriter.java
  src/main/java/com/codingnomads/betty/data/batch/matchoddsjob/FootballMatchJpaReader.java
  src/main/java/com/codingnomads/betty/data/batch/matchoddsjob/MatchOddsRdsWriter.java
  src/main/java/com/codingnomads/betty/data/batch/matchoddsjob/MatchToOddsProcessor.java
  src/main/java/com/codingnomads/betty/data/models/FootballMatchInfo.java
  src/main/java/com/codingnomads/betty/data/models/MatchOdds.java
  src/main/java/com/codingnomads/betty/logic/interfaces/GameInformationRepository.java
  src/main/java/com/codingnomads/betty/logic/interfaces/MatchOddsJpaRepository.java
  src/main/java/com/codingnomads/betty/logic/services/FootballMatchInfoService.java
  src/main/java/com/codingnomads/betty/logic/services/GameInformationService.java
  src/main/java/com/codingnomads/betty/logic/services/MatchOddsService.java
  src/main/java/com/codingnomads/betty/presentation/controller/OddsByMatchController.java
  src/test/java/com/codingnomads/betty/data/api/GameInformationAPIRepositoryTests.java
  src/test/java/com/codingnomads/betty/data/batch/batchprocessors/FootballMatchProcessorTests.java
  src/test/java/com/codingnomads/betty/data/batch/batchprocessors/MatchToOddsProcessorTests.java
  src/test/java/com/codingnomads/betty/data/batch/batchreaders/FootballMatchApireaderTests.java
  src/test/java/com/codingnomads/betty/data/batch/batchreaders/FootballMatchJpaReaderTests.java
  src/test/java/com/codingnomads/betty/data/batch/batchwriters/FootballMatchRdsWriterTests.java
  src/test/java/com/codingnomads/betty/data/batch/batchwriters/MatchOddsRdsWriterTests.java
  src/test/java/com/codingnomads/betty/logic/services/FootballMatchInfoServiceTests.java
  src/test/java/com/codingnomads/betty/logic/services/GameInformationServiceTest.java
  src/test/java/com/codingnomads/betty/logic/services/MatchOddsServiceTests.java
  src/test/java/com/codingnomads/betty/presentation/controller/OddsByMatchControllerTest.java
Labels: Ready to Merge

#55 Eileen/automate query constructor
  src/main/java/com/codingnomads/betty/logic/interfaces/TwitterKeywordRepository.java
  src/main/java/com/codingnomads/betty/logic/services/TwitterQueryConstructor.java
  src/test/java/com/codingnomads/betty/logic/services/TwitterQueryConstructorTest.java
Labels: Comments pending, Ready to Merge

#56 Cleaned up services and repos
  src/main/java/com/codingnomads/betty/configurations/RestTemplateConfigure.java
  src/main/java/com/codingnomads/betty/configurations/SpringBatchConfig.java
  src/main/java/com/codingnomads/betty/configurations/TwitterConfig.java
  src/main/java/com/codingnomads/betty/data/api/GameInformationAPIRepository.java
  src/main/java/com/codingnomads/betty/data/api/TwitterSourceMinerRepository.java
  src/main/java/com/codingnomads/betty/data/batch/footballmatchjob/exceptions/EmptyItemException.java
  src/main/java/com/codingnomads/betty/data/rds/AmazonRdsRepository.java
  src/main/java/com/codingnomads/betty/data/repositories/TwitterRepository.java
  src/main/java/com/codingnomads/betty/logic/exceptions/InvalidInputException.java
  src/main/java/com/codingnomads/betty/logic/exceptions/InvalidScoreException.java
  src/main/java/com/codingnomads/betty/logic/exceptions/JSONNotFoundException.java
  src/main/java/com/codingnomads/betty/logic/exceptions/TwitterSearchFailedException.java
  src/main/java/com/codingnomads/betty/logic/interfaces/FootballMatchesInfoJpaRepository.java
  src/main/java/com/codingnomads/betty/logic/interfaces/GameInformationRepository.java
  src/main/java/com/codingnomads/betty/logic/interfaces/MatchOddsJpaRepository.java
  src/main/java/com/codingnomads/betty/logic/interfaces/TwitterJpaRepository.java
  src/main/java/com/codingnomads/betty/logic/interfaces/TwitterMinerRepository.java
  src/main/java/com/codingnomads/betty/logic/models/betapimodels/EventJSON.java
  src/main/java/com/codingnomads/betty/logic/models/betapimodels/GameInformationJSON.java
  src/main/java/com/codingnomads/betty/logic/models/betapimodels/MarketJSON.java
  src/main/java/com/codingnomads/betty/logic/models/betapimodels/PriceJSON.java
  src/main/java/com/codingnomads/betty/logic/models/betapimodels/RunnerJSON.java
  src/main/java/com/codingnomads/betty/logic/services/FootballMatchInfoService.java
  src/main/java/com/codingnomads/betty/logic/services/MatchOddsService.java
  src/main/java/com/codingnomads/betty/logic/services/ProbabilityToWinService.java
  src/main/java/com/codingnomads/betty/logic/services/ProcessTweetsThroughNlpService.java
  src/main/java/com/codingnomads/betty/logic/services/SentimentAnalyserService.java
  src/main/java/com/codingnomads/betty/logic/services/SourceToResultPipelineService.java
  src/main/java/com/codingnomads/betty/logic/services/TwitterService.java
  src/main/java/com/codingnomads/betty/presentation/controller/HomeController.java
  src/main/java/com/codingnomads/betty/presentation/controller/SearchController.java
  src/main/java/com/codingnomads/betty/presentation/webmodel/InputTeam.java
  src/main/resources/templates/api-to-database.html
  src/main/resources/templates/display-sentiment-score.html
  src/main/resources/templates/displayOdds.html
  src/main/resources/templates/index.html
  src/test/java/com/codingnomads/betty/data/api/GameInformationAPIRepositoryTests.java
  src/test/java/com/codingnomads/betty/logic/services/FootballMatchInfoServiceTests.java
  src/test/java/com/codingnomads/betty/logic/services/MatchOddsServiceTests.java
  src/test/java/com/codingnomads/betty/logic/services/TwitterServiceTests.java
  src/test/java/com/codingnomads/betty/presentation/controller/SearchControllerTest.java
Labels: Ready to Merge
